#!/usr/bin/env python
# Copyright 2014-2020 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Qiming Sun <osirpt.sun@gmail.com>
#

'''
Trying to implement the FCI solver with complex Hamiltonian but with alpha-beta
degeneracy.
'''

import warnings
import ctypes
import numpy as np
import scipy.linalg

from pyscf import lib, ao2mo
from pyscf.fci import cistring, direct_spin1
from pyscf.fci.addons import _unpack_nelec

from mrh.my_pyscf.pbc.fci import rdm_helper
from mrh.my_pyscf.pbc.fci import spin_op

logger = lib.logger
libfci = direct_spin1.libfci

# Some global variables
HDIAG_IMAG_TOL = 1e-3
IMAG_NOISE = 1e-12
HERMI_THRESH = 1e-6

def get_init_guess_cplx(norb, nelec, nroots, hdiag):
    '''
    Get the initial guess for the FCI calculation in the complex CI basis.
    The initial guess is generated by the real FCI code, and then add a small
    imag noise. I believe that would be a good guess.
    '''
    dtype = hdiag.dtype
    neleca, nelecb = _unpack_nelec(nelec)
    na = cistring.num_strings(norb, neleca)
    nb = cistring.num_strings(norb, nelecb)
    ci0 = direct_spin1._get_init_guess(na, nb, nroots, hdiag.real, nelec)
    ci0out = []
    for i in range(nroots):
        ciout = ci0[i].astype(dtype)
        ciout.real = ci0[i]
        ciout.imag = IMAG_NOISE
        ciout /= np.linalg.norm(ciout)
        ci0out.append(ciout)
    ci0 = None
    return ci0out

def contract_1e(h1e, fcivec, norb, nelec, link_index=None):
    '''
    Contract the 1-electron Hamiltonian with a FCI vector to get a new FCI vector.
    args:
        h1e: np.ndarray (norb, norb)
            1-electron Hamiltonian matrix in the MO basis (complex)
        fcivec: np.ndarray (ndet,)
            FCI vector to be contracted (complex)
        norb: int
            number of orbitals
        nelec: int or tuple
            number of electrons
        link_index: tuple (Currently stored without trilidx)
            link index for the FCI vector
    returns:
        h1e_fcivec: np.ndarray (ndet,)
            the result of contracting h1e with fcivec, i.e. h1e_fcivec = h1e * fcivec
    '''
    link_indexa, link_indexb = _unpack(norb, nelec, link_index)
    na, nlinka = link_indexa.shape[:2]
    nb, nlinkb = link_indexb.shape[:2]
    assert fcivec.size == na*nb

    if fcivec.dtype == h1e.dtype == np.float64:
        fcivec = np.asarray(fcivec, order='C')
        h1e = np.asarray(h1e, order='C')
        ci1 = np.zeros_like(fcivec)
        libfci.FCIcontract_a_1e_nosym(h1e.ctypes.data_as(ctypes.c_void_p),
                                fcivec.ctypes.data_as(ctypes.c_void_p),
                                ci1.ctypes.data_as(ctypes.c_void_p),
                                ctypes.c_int(norb),
                                ctypes.c_int(na), ctypes.c_int(nb),
                                ctypes.c_int(nlinka), ctypes.c_int(nlinkb),
                                link_indexa.ctypes.data_as(ctypes.c_void_p),
                                link_indexb.ctypes.data_as(ctypes.c_void_p))
        libfci.FCIcontract_b_1e_nosym(h1e.ctypes.data_as(ctypes.c_void_p),
                                fcivec.ctypes.data_as(ctypes.c_void_p),
                                ci1.ctypes.data_as(ctypes.c_void_p),
                                ctypes.c_int(norb),
                                ctypes.c_int(na), ctypes.c_int(nb),
                                ctypes.c_int(nlinka), ctypes.c_int(nlinkb),
                                link_indexa.ctypes.data_as(ctypes.c_void_p),
                                link_indexb.ctypes.data_as(ctypes.c_void_p))
        return ci1.view(direct_spin1.FCIvector)

    link_indexa, link_indexb = _unpack(norb, nelec, link_index)
    ciR = contract_1e(h1e.real, fcivec.real, norb, nelec, link_index=link_index)
    ciR -= contract_1e(h1e.imag, fcivec.imag, norb, nelec, link_index=link_index)
    ciI = contract_1e(h1e.real, fcivec.imag, norb, nelec, link_index=link_index)
    ciI += contract_1e(h1e.imag, fcivec.real, norb, nelec, link_index=link_index)

    ci1 = ciR.astype(np.complex128)
    ci1.real = ciR
    ci1.imag = ciI
    return ci1

def contract_2e(eri, fcivec, norb, nelec, link_index=None):
    direct_spin1.contract_2e.__doc__ + '''
    args:
        eri: np.ndarray (norb, norb, norb, norb)
            2-electron integrals in the MO basis (complex)
        fcivec: np.ndarray (ndet,)
            FCI vector to be contracted (complex)
        norb: int
            number of orbitals
        nelec: int or tuple
            number of electrons
        link_index: tuple (Currently stored without trilidx)
            link index for the FCI vector
    returns:
        h2e_fcivec: np.ndarray (ndet,)
            the result of contracting eri with fcivec, i.e. h2e_fcivec = eri * fcivec
    '''
    link_indexa, link_indexb = _unpack(norb, nelec, link_index)
    na, nlinka = link_indexa.shape[:2]
    nb, nlinkb = link_indexb.shape[:2]
    assert fcivec.size == na*nb
    if fcivec.dtype == eri.dtype == np.float64:
        fcivec = np.asarray(fcivec, order='C')
        eri = np.asarray(eri, order='C')
        ci1 = np.zeros_like(fcivec)

        libfci.FCIcontract_2es1(eri.ctypes.data_as(ctypes.c_void_p),
                                fcivec.ctypes.data_as(ctypes.c_void_p),
                                ci1.ctypes.data_as(ctypes.c_void_p),
                                ctypes.c_int(norb),
                                ctypes.c_int(na), ctypes.c_int(nb),
                                ctypes.c_int(nlinka), ctypes.c_int(nlinkb),
                                link_indexa.ctypes.data_as(ctypes.c_void_p),
                                link_indexb.ctypes.data_as(ctypes.c_void_p))
        return ci1.view(direct_spin1.FCIvector)

    ciR = np.asarray(fcivec.real, order='C')
    ciI = np.asarray(fcivec.imag, order='C')
    eriR = np.asarray(eri.real, order='C')
    eriI = np.asarray(eri.imag, order='C')
    link_index = (link_indexa, link_indexb)
    outR  = contract_2e(eriR, ciR, norb, nelec, link_index=link_index)
    outR -= contract_2e(eriI, ciI, norb, nelec, link_index=link_index)
    outI  = contract_2e(eriR, ciI, norb, nelec, link_index=link_index)
    outI += contract_2e(eriI, ciR, norb, nelec, link_index=link_index)
    out = outR.astype(np.complex128)
    out.real = outR
    out.imag = outI
    return out

def absorb_h1e(h1e, eri, norb, nelec, fac=1):
    '''
    Modify 2e Hamiltonian to include 1e Hamiltonian contribution.
    '''
    if not isinstance(nelec, (int, np.number)):
        nelec = sum(nelec)
    if h1e.dtype == eri.dtype == np.float64:
        h2e = ao2mo.restore(1, eri.copy(), norb)
    else:
        assert eri.ndim == 4
        h2e = eri.astype(dtype=np.result_type(h1e, eri), copy=True)
    
    J = np.einsum('jiik->jk', h2e)
    # J = 0.5 * (J + J.conj().T)
    f1e = h1e - J * .5
    f1e = f1e * (1./(nelec+1e-100))
    # f1e = 0.5 * (f1e + f1e.conj().T)
    for k in range(norb):
        h2e[k,k,:,:] += f1e
        h2e[:,:,k,k] += f1e
    
    if fac != 1:
        h2e *= fac
    
    return h2e

def pspace(h1e, eri, norb, nelec, hdiag=None, pspace_size=400):
    '''
    pspace Hamiltonian to improve Davidson preconditioner. See, CPL, 169, 463
    Construct the explicit Hamiltonian in subspace and then diagonalize it to get
    the eigenvalues and eigenvectors.
    I can not directly use the direct_spin1.pspace as the h0 = h_real + i*h_imag,
    h_real is hermitian while h_imag is anti-hermitian to make h0 hermitian.
    '''
    if norb >= 64:
        raise NotImplementedError('norb >= 64')
    
    assert np.iscomplexobj(h1e) and np.iscomplexobj(eri)
    assert eri.ndim == 4 and h1e.ndim == 2

    neleca, nelecb = _unpack_nelec(nelec)
    h1e = np.ascontiguousarray(h1e)
    eri = np.ascontiguousarray(eri)
    na = cistring.num_strings(norb, neleca)
    nb = cistring.num_strings(norb, nelecb)
    if hdiag is None:
        hdiag = make_hdiag(h1e, eri, norb, nelec, compress=False)
    assert hdiag.size == na * nb
    if hdiag.size <= pspace_size:
            addr = np.arange(hdiag.size)
    else:
        try:
            addr = np.argpartition(hdiag, pspace_size-1)[:pspace_size].copy()
        except AttributeError:
            addr = np.argsort(hdiag)[:pspace_size].copy()

    addra, addrb = divmod(addr, nb)
    stra = cistring.addrs2str(norb, neleca, addra)
    strb = cistring.addrs2str(norb, nelecb, addrb)
    pspace_size = len(addr)
    
    def _built_h0(h1e, eri):
        dtype = h1e.dtype
        h0R = np.zeros((pspace_size,pspace_size), dtype=dtype)
        h1eR = h1e.astype(dtype=dtype)
        eriR = eri.astype(dtype=dtype)
        libfci.FCIpspace_h0tril(h0R.ctypes.data_as(ctypes.c_void_p),
                                h1eR.ctypes.data_as(ctypes.c_void_p),
                                eriR.ctypes.data_as(ctypes.c_void_p),
                                stra.ctypes.data_as(ctypes.c_void_p),
                                strb.ctypes.data_as(ctypes.c_void_p),
                                ctypes.c_int(norb), ctypes.c_int(pspace_size))
        return h0R
    
    h0real = _built_h0(h1e.real, eri.real)
    h0real = lib.hermi_triu(h0real, 1)
    h0imag = _built_h0(h1e.imag, eri.imag)
    h0imag = lib.hermi_triu(h0imag, 2) # It is antihermitian
    
    h0 = h0real.astype(h1e.dtype)
    h0.real = h0real
    h0.imag = h0imag
    
    del h0real, h0imag
    
    idx = np.arange(pspace_size)
    h0.real[idx,idx] = hdiag.real[addr]
    h0.imag[idx,idx] = hdiag.imag[addr]

    del idx

    return addr, h0

def energy(h1e, eri, fcivec, norb, nelec, link_index=None):
    r'''
    Compute the FCI electronic energy for given complex Hamiltonian and 
    complex FCI vector.
    sigma  = (H.real + i H.imag)(ci.real + i ci.imag)
          &= (H.real ci.real - H.imag ci.imag) + i (H.real ci.imag + H.imag ci.real)
    e = <ci|H|ci> = ci^dagger sigma
    '''
    assert np.iscomplexobj(h1e) and np.iscomplexobj(eri)
    h1e = np.asarray(h1e)
    eri = np.asarray(eri)
    ci  = np.asarray(fcivec)
    h2e_eff = absorb_h1e(h1e, eri, norb, nelec, fac=0.5)
    sigma = contract_2e(h2e_eff, ci, norb, nelec, link_index=link_index)
    e = np.vdot(ci, sigma)
    return e

def make_hdiag(h1e, eri, norb, nelec, compress=False):
    '''
    Diagonal of the FCI Hamiltonian.
    I guess, the real Hamiltonian would be a good approximation to the complex one.
    '''
    assert np.iscomplexobj(h1e) and np.iscomplexobj(eri)
    hdiag_real = direct_spin1.make_hdiag(h1e.real, eri.real, norb, nelec, compress)
    hdiag = hdiag_real.astype(h1e.dtype)
    hdiag.real = hdiag_real
    hdiag_real = None
    return hdiag

def make_rdm1s(fcivec, norb, nelec, link_index=None):
    make_rdm1s.__doc__ = direct_spin1.make_rdm1s.__doc__ + '''
    Compute the spin-separated 1-RDMs for a complex FCI vector using the backend C function.
    '''
    link_index = _unpack(norb, nelec, link_index)
    rdm1a = rdm_helper.make_rdm1_spin1('FCImake_rdm1a_cplx', fcivec, fcivec,
                                norb, nelec, link_index)
    rdm1b = rdm_helper.make_rdm1_spin1('FCImake_rdm1b_cplx', fcivec, fcivec,
                                norb, nelec, link_index)
    return (rdm1a, rdm1b)

def make_rdm1(fcivec, norb, nelec, link_index=None):
    make_rdm1.__doc__ = direct_spin1.make_rdm1.__doc__ + '''
    Spin-summed 1-RDM for a complex FCI vector.
    #TODO: Implemented the spins-summed excitation operator in backend C code.
    '''

    rdm1a, rdm1b = make_rdm1s(fcivec, norb, nelec, link_index)
    rdm1 = rdm1a + rdm1b
    return rdm1.conj().T

def make_rdm12s(fcivec, norb, nelec, link_index=None, reorder=True):
    make_rdm12s.__doc__ = direct_spin1.make_rdm12s.__doc__ + '''
    Compute the spin-separated 1-RDMs and 2-RDMs for a complex FCI vector using the backend C function.
    '''
    dm1a, dm2aa = rdm_helper.make_rdm12_spin1('FCIrdm12kern_a_cplx', fcivec, fcivec,
                                       norb, nelec, link_index, 1)
    dm1b, dm2bb = rdm_helper.make_rdm12_spin1('FCIrdm12kern_b_cplx', fcivec, fcivec,
                                       norb, nelec, link_index, 1)
    _, dm2ab = rdm_helper.make_rdm12_spin1('FCItdm12kern_ab_cplx', fcivec, fcivec,
                                    norb, nelec, link_index, 0)
    if reorder:
        dm1a, dm2aa = rdm_helper.reorder_rdm(dm1a, dm2aa, inplace=True)
        dm1b, dm2bb = rdm_helper.reorder_rdm(dm1b, dm2bb, inplace=True)
    
    return (dm1a, dm1b), (dm2aa, dm2ab, dm2bb)

def make_rdm12(fcivec, norb, nelec, link_index=None, reorder=True):
    make_rdm12.__doc__ = direct_spin1.make_rdm12.__doc__
    # TODO: Need to implement this in backend C code.
    # dm1, dm2 = rdm_helper.make_rdm12_spin1('FCIrdm12kern_sf_cplx', fcivec, fcivec,
    #                                 norb, nelec, link_index, 1)
    # if reorder:
    #    dm1, dm2 = rdm_helper.reorder_rdm(dm1, dm2, inplace=True)
    dm1, dm2 = rdm_helper.make_rdm12_cplx(fcivec, norb, nelec, link_index, 1,)
    return dm1, dm2

def make_rdm1s_py(fcivec, norb, nelec, link_index=None):
    rdm1a, rdm1b = rdm_helper.make_rdm1s_cplx(fcivec, norb, nelec, link_index)
    return rdm1a, rdm1b

def make_rdm1_py(fcivec, norb, nelec, link_index=None):
    rdm1 = rdm_helper.make_rdm1_cplx(fcivec, norb, nelec, link_index)
    return rdm1

def make_rdm12s_py(fcivec, norb, nelec, link_index=None, reorder=True):
    (dm1a, dm1b), (dm2aa, dm2ab, dm2bb) = \
        rdm_helper.make_rdm12s_cplx(fcivec, norb, nelec, link_index, reorder)
    return (dm1a, dm1b), (dm2aa, dm2ab, dm2bb)

def make_rdm12_py(fcivec, norb, nelec, link_index=None, reorder=True):
    dm1, dm2 = rdm_helper.make_rdm12_cplx(fcivec, norb, nelec, link_index, reorder)
    return dm1, dm2

def _make_diag_precond(hdiag, level_shift=1e-3):
    '''
    Diagonal preconditioner for the Davidson solver.
    This is main function to generate the diagonal preconditioner but I need
    to write the wrapper around this to match the pyscf.
    '''
    hdiag = np.asarray(hdiag)
    if np.max(np.abs(hdiag.imag)) > HDIAG_IMAG_TOL:
        msg = ("The diagonal elements of the Hamiltonian have non-negligible "
            f"imaginary parts: max |Im(hdiag)| = {np.max(np.abs(hdiag.imag))}.")
        warnings.warn(msg)
    def precond(dx, e, *args):
        diagd = hdiag - (np.real(e) - level_shift)
        diagd = diagd.copy()
        diagd[np.abs(diagd) < 1e-8] = 1e-8
        return dx / diagd
    return precond

# The Davidson solver is used for iterative solving the eigen vectos for the a large sparse matrix.
# Initially, a few guess vectors are provided, then in each iteration, the matrix-vector product is 
# computed and then the subspace Hamiltonian is constructed and diagonalized to get the Ritz values 
# and Ritz vectors, then the residual is computed and preconditioned to get the new guess vector for 
# the next iteration. Till the convergence is reached.
# Alternatively, in QC, there is pspace Davidson solver, where the Hamiltonian is constructed in a smaller 
# subspace exactly and then those eigenvectors are projected to entire subspace and been used for the 
# Davidson solver. Below I am defining the preconditioners for the Davidson solvers.

def make_diag_precond(hdiag, pspaceig, pspaceci, addr, level_shift=0):
    # To make it compatible with direct_spin1
    return _make_diag_precond(hdiag, level_shift)

def make_pspace_precond(hdiag, pspaceig, pspaceci, addr, level_shift=0):
    '''
    Code adapated from the pyscf/fci/direct_spin1.py, but with some modification 
    to handle the complex Hamiltonian.
    args:
        hdiag: np.ndarray of shape (ndet,)
            diagonal of the Hamiltonian in the determinant basis.
        pspaceig: np.ndarray of shape (npsp,)
            eigenvalues of the Hamiltonian in the pspace.
        pspaceci: np.ndarray of shape (npsp, npsp)
            eigenvectors of the Hamiltonian in the pspace.
        addr: np.ndarray of shape (npsp,)
            the addresses of the determinants in the pspace.
        level_shift: float
            level shift for the preconditioner, default is 0.
    returns:
        precond: function
            the preconditioner function that can be used in the Davidson solver.
    '''
    hdiag = np.asarray(hdiag)
    pspaceig = np.asarray(pspaceig)
    pspaceci = np.asarray(pspaceci)
    addr = np.asarray(addr)

    def precond(r, e0, x0, *args):
        r = np.asarray(r)
        x0 = np.asarray(x0)
        e0r = np.real(e0)

        # Full-space diagonal inverse
        denom = hdiag - (e0r - level_shift)
        denom = denom.astype(hdiag.dtype, copy=True)
        
        # For very small denominators, lets set them to a small number to 
        # avoid numerical instability. 
        denom[np.abs(denom) < 1e-8] = 1e-8 + 0j

        hdiaginv = 1.0 / denom
        hdiaginv[np.abs(hdiaginv) > 1e8] = 1e8

        # P-space inverse in eigenbasis:
        pdenom = pspaceig - (e0r - level_shift)
        pdenom = np.asarray(pdenom, dtype=pspaceig.dtype).copy()
        pdenom[np.abs(pdenom) < 1e-8] = 1e-8
        h0e0inv = np.dot(pspaceci / pdenom, pspaceci.conj().T)

        # Apply preconditioner to x0 and residual
        h0x0 = x0 * hdiaginv
        h0x0[addr] = np.dot(h0e0inv, x0[addr])

        h0r = r * hdiaginv
        h0r[addr] = np.dot(h0e0inv, r[addr])

        # For complex number innder product, using vdot instead of dot.
        denom_e1 = np.vdot(x0, h0x0)
        if abs(denom_e1) < 1e-14: e1 = 0.0
        else: e1 = np.vdot(x0, h0r) / denom_e1
        x1 = r - e1 * x0
        x1 *= hdiaginv
        return x1
    return precond

def kernel_ms1(fci, h1e, eri, norb, nelec, ci0=None, link_index=None,
               tol=None, lindep=None, max_cycle=None, max_space=None,
               nroots=None, davidson_only=None, pspace_size=None, hop=None,
               max_memory=None, verbose=None, ecore=0, **kwargs):
    direct_spin1.kernel_ms1.__doc__ + '''
    Note: I can not directly use the direct_spin1.kernel_ms1 as that is not compatiable with the complex 
    Hamiltonian. I am adding this function here most of the code is same as that of direct_spin1.kernel_ms1, 
    but with some modification to handle the complex Hamiltonian.
    '''
    assert np.iscomplexobj(h1e) and np.iscomplexobj(eri)

    if nroots is None: nroots = fci.nroots
    if davidson_only is None: davidson_only = fci.davidson_only
    if pspace_size is None: pspace_size = fci.pspace_size
    if max_memory is None: max_memory = fci.max_memory - lib.current_memory()[0]
    
    log = logger.new_logger(fci, verbose)
    nelec = _unpack_nelec(nelec, fci.spin)
    
    assert (0 <= nelec[0] <= norb and 0 <= nelec[1] <= norb)

    hdiag = fci.make_hdiag(h1e, eri, norb, nelec, compress=False).ravel()
    num_dets = hdiag.size
    pspace_size = min(num_dets, pspace_size)
    addr = [0]
    pw = pv = None
    if pspace_size > 0 and norb < 64:
        addr, h0 = fci.pspace(h1e, eri, norb, nelec, hdiag, pspace_size)
        pw, pv = fci.eig(h0)
        pspace_size = len(addr)

    if getattr(fci, 'sym_allowed_idx', None):
        sym_idx = np.hstack(fci.sym_allowed_idx)
        civec_size = sym_idx.size
    else:
        sym_idx = None
        civec_size = num_dets

    if max_memory < civec_size*6*16e-6:
        log.warn('Not enough memory for FCI solver. '
                 'The minimal requirement is %.0f MB', civec_size*120e-6)

    if pspace_size >= civec_size and ci0 is None and not davidson_only:
        if nroots > 1:
            nroots = min(civec_size, nroots)
            civec = np.empty((nroots,civec_size), dtype=h1e.dtype)
            civec[:,addr] = pv[:,:nroots].T
            return pw[:nroots]+ecore, civec
        
        elif pspace_size == 1 or abs(pw[0]-pw[1]) > 1e-12:
            civec = np.empty(civec_size, dtype = h1e.dtype)
            civec[addr] = pv[:,0]
            return pw[0]+ecore, civec
        
    pw = pv = h0 = None

    if sym_idx is None:
        precond = fci.make_precond(hdiag)
    else:
        precond = fci.make_precond(hdiag[sym_idx])

    h2e = fci.absorb_h1e(h1e, eri, norb, nelec, 0.5)

    if hop is None:
        cpu0 = [logger.process_clock(), logger.perf_counter()]
        def hop(c):
            hc = fci.contract_2e(h2e, c, norb, nelec, link_index)
            cpu0[:] = log.timer_debug1('contract_2e', *cpu0)
            return hc.ravel()

    def init_guess():
        if callable(getattr(fci, 'get_init_guess', None)):
            return fci.get_init_guess(norb, nelec, nroots, hdiag)
        else:
            x0 = []
            for i in range(min(len(addr), nroots)):
                x = np.zeros(civec_size)
                x[addr[i]] = 1
                x0.append(x)
            return x0

    if ci0 is None:
        ci0 = init_guess  # lazy initialization to reduce memory footprint
    elif not callable(ci0):
        if isinstance(ci0, np.ndarray):
            ci0 = [ci0.ravel()]
        else:
            ci0 = [x.ravel() for x in ci0]
        if sym_idx is not None and ci0[0].size != civec_size:
            ci0 = [x[sym_idx] for x in ci0]
        if len(ci0) < nroots:
            ci0.extend(init_guess()[len(ci0):])

    if tol is None: tol = fci.conv_tol
    if lindep is None: lindep = fci.lindep
    if max_cycle is None: max_cycle = fci.max_cycle
    if max_space is None: max_space = fci.max_space
    tol_residual = getattr(fci, 'conv_tol_residual', None)

    with lib.with_omp_threads(fci.threads):
        e, c = fci.eig(hop, ci0, precond, tol=tol, lindep=lindep,
                       max_cycle=max_cycle, max_space=max_space, nroots=nroots,
                       max_memory=max_memory, verbose=log, follow_state=True,
                       tol_residual=tol_residual, **kwargs)
    return e+ecore, c

class FCISolver(direct_spin1.FCISolver):
    def __init__(self, *args, **kwargs):
        direct_spin1.FCISolver.__init__(self, *args, **kwargs)
        self.davidson_only = True

    def contract_1e(self, h1e, fcivec, norb, nelec, link_index=None):
        return contract_1e(h1e, fcivec, norb, nelec, link_index)

    def contract_2e(self, eri, fcivec, norb, nelec, link_index=None):
        return contract_2e(eri, fcivec, norb, nelec, link_index)

    def absorb_h1e(self, h1e, eri, norb, nelec, fac=1):
        return absorb_h1e(h1e, eri, norb, nelec, fac)

    def energy(self, h1e, eri, fcivec, norb, nelec, link_index=None):
        return energy(h1e, eri, fcivec, norb, nelec, link_index)
    
    def make_hdiag(self, h1e, eri, norb, nelec, compress=False):
        nelec = direct_spin1._unpack_nelec(nelec, self.spin)
        return make_hdiag(h1e, eri, norb, nelec, compress)
    
    def pspace(self, h1e, eri, norb, nelec, hdiag=None, pspace_size=400):
        nelec = _unpack_nelec(nelec, self.spin)
        return pspace(h1e, eri, norb, nelec, hdiag, pspace_size)
    
    def make_precond(self, hdiag, pspaceig=None, pspaceci=None, addr=None):
        if pspaceig is None:
            return make_diag_precond(hdiag, pspaceig, pspaceci, addr,
                                     self.level_shift)
        else:
            return make_pspace_precond(hdiag, pspaceig, pspaceci, addr,
                                       self.level_shift)
        
    def kernel(self, h1e, eri, norb, nelec, ci0=None,
               tol=None, lindep=None, max_cycle=None, max_space=None,
               nroots=None, davidson_only=None, pspace_size=None,
               orbsym=None, wfnsym=None, ecore=0, **kwargs):
        link_indexa, link_indexb = _unpack(norb, nelec, None)

        # TODO: write the kernel_ms1 to avoid any warnings.
        e, c = kernel_ms1(self, h1e, eri, norb, nelec, ci0,
                          (link_indexa,link_indexb), tol=tol, 
                          lindep=lindep, max_cycle=max_cycle, max_space=max_space,
                          nroots=nroots, davidson_only=davidson_only, pspace_size=pspace_size, 
                            ecore=ecore, **kwargs)
        self.eci, self.ci = e, c
        return e, c

    def eig(self, op, x0=None, precond=None, **kwargs):
        if isinstance(op, np.ndarray):
            try:
                assert np.max(op - op.conj().T) < HERMI_THRESH, "The Hamiltonian matrix is not hermitian."
                self.converged = True
                return scipy.linalg.eigh(op)
            except Exception as e:
                raise RuntimeError(f"Failed to diagonalize matrix: {e}")

        self.converged, e, ci = \
                lib.davidson1(lambda xs: [op(x) for x in xs],
                              x0, precond, lessio=self.lessio, **kwargs)

        if kwargs.get('nroots', 1) == 1:
            self.converged = self.converged[0]
            e = e[0]
            ci = ci[0]
        return e, ci

    def make_rdm1s(self, fcivec, norb, nelec, link_index=None):
        return make_rdm1s(fcivec, norb, nelec, link_index)
    
    def make_rdm1(self, fcivec, norb, nelec, link_index=None):
        return make_rdm1(fcivec, norb, nelec, link_index)
    
    def make_rdm12s(self, fcivec, norb, nelec, link_index=None, reorder=True):
        return make_rdm12s(fcivec, norb, nelec, link_index, reorder)
    
    def make_rdm12(self, fcivec, norb, nelec, link_index=None, reorder=True):
        return make_rdm12(fcivec, norb, nelec, link_index, reorder)

    def get_init_guess(self, norb, nelec, nroots, hdiag):
        return get_init_guess_cplx(norb, nelec, nroots, hdiag)
    
    def make_rdm1s_py(self, fcivec, norb, nelec, link_index=None):
        return make_rdm1s_py(fcivec, norb, nelec, link_index)
    
    def make_rdm1_py(self, fcivec, norb, nelec, link_index=None):
        return make_rdm1_py(fcivec, norb, nelec, link_index)
    
    def make_rdm12s_py(self, fcivec, norb, nelec, link_index=None, reorder=True):
        return make_rdm12s_py(fcivec, norb, nelec, link_index, reorder)
    
    def make_rdm12_py(self, fcivec, norb, nelec, link_index=None, reorder=True):
        return make_rdm12_py(fcivec, norb, nelec, link_index, reorder)
    
    def contract_ss(self, fcivec, norb, nelec):
        nelec = _unpack_nelec(nelec, self.spin)
        return spin_op.contract_ss0(fcivec, norb, nelec)
    
    def spin_square(self, fcivec, norb, nelec):
        return spin_op.spin_square0(fcivec, norb, nelec)

FCI = FCISolver

def _unpack(norb, nelec, link_index, spin=None):
    if link_index is None:
        neleca, nelecb = _unpack_nelec(nelec, spin)
        link_indexa = cistring.gen_linkstr_index(range(norb), neleca)
        link_indexb = cistring.gen_linkstr_index(range(norb), nelecb)
        return link_indexa, link_indexb
    else:
        return link_index