"""Periodic MC-PDFT energy methods for kLAS wave functions.

This module specializes the existing k-MC-PDFT implementation for density
matrices produced by periodic LASCI and LASSCF.  kLAS RDMs and active-space
integrals use a Wannier basis, so the corresponding kLAS ``mo_phase`` is
carried explicitly into every basis transformation.
"""

import numpy as np

from pyscf.lib import logger
from pyscf.pbc.lib import kpts_helper

from mrh.my_pyscf.pbc.mcpdft import klaspdft_helper
from mrh.my_pyscf.pbc.mcpdft import kmcpdft
from mrh.my_pyscf.pbc.mcpdft.kmcpdft import _kMCPDFT
from mrh.my_pyscf.pbc.mcpdft.otfnalperiodic import _energy_ot_from_kpts


def energy_mcwfn_klas(mc, mo_coeff=None, ci=None, ot=None, state=0,
                      casdm1s=None, casdm2=None, verbose=None,
                      mo_phase=None):
    """Evaluate the MC-wavefunction energy from kLAS Wannier RDMs.

    This is the conventional dense-Wannier k-MC-PDFT energy expression with
    two kLAS-specific inputs: the phase generated by the kLAS Wannier routine
    and the full active-space integrals returned by ``get_h2cas``.
    """
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    if ci is None:
        ci = mc.ci
    if casdm1s is None or casdm2 is None:
        built_dm1s, built_dm2 = klaspdft_helper.make_one_casdm12_klas(
            mc, ci=ci, state=state,
        )
        if casdm1s is None:
            casdm1s = built_dm1s
        if casdm2 is None:
            casdm2 = built_dm2
    if mo_phase is None:
        mo_phase = klaspdft_helper.get_klas_mo_phase(
            mc, mo_coeff=mo_coeff,
        )
    h2eff = mc.get_h2cas(mo_coeff)
    return kmcpdft.energy_mcwfn(
        mc,
        mo_coeff=mo_coeff,
        ci=ci,
        ot=ot,
        state=state,
        casdm1s=casdm1s,
        casdm2=casdm2,
        verbose=verbose,
        mo_phase=mo_phase,
        h2eff=h2eff,
    )


def energy_dft_klas(mc, mo_coeff=None, ci=None, ot=None, state=0,
                    casdm1s=None, casdm2=None, max_memory=None, hermi=1,
                    mo_phase=None):
    """Evaluate the on-top functional from kLAS Wannier density matrices."""
    if ot is None:
        ot = mc.otfnal
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    if ci is None:
        ci = mc.ci
    if casdm1s is None or casdm2 is None:
        built_dm1s, built_dm2 = klaspdft_helper.make_one_casdm12_klas(
            mc, ci=ci, state=state,
        )
        if casdm1s is None:
            casdm1s = built_dm1s
        if casdm2 is None:
            casdm2 = built_dm2
    if mo_phase is None:
        mo_phase = klaspdft_helper.get_klas_mo_phase(
            mc, mo_coeff=mo_coeff,
        )
    if max_memory is None:
        max_memory = mc.max_memory

    kconserv = getattr(mc, "kconserv", None)
    if kconserv is None:
        kconserv = kpts_helper.get_kconserv(mc.cell, mc.kpts)
    casdm1s_kpts, cascm2_kpts = \
        klaspdft_helper.make_klas_rdms_kpts(
            casdm1s, casdm2, mo_phase, kconserv,
        )
    return _energy_ot_from_kpts(
        ot,
        casdm1s_kpts,
        cascm2_kpts,
        mo_coeff,
        mc.ncore,
        kconserv,
        max_memory=max_memory,
        hermi=hermi,
    )


def energy_tot_klas(mc, mo_coeff=None, ci=None, ot=None, state=0,
                    verbose=None, **kwargs):
    """Build one kLAS RDM pair and evaluate its total MC-PDFT energy.

    The expensive product-state RDMs and the gauge-defining ``mo_phase`` are
    each constructed once and shared by the MC-wavefunction and on-top energy
    paths.
    """
    del kwargs
    if ot is None:
        ot = mc.otfnal
    ot.reset(mol=mc.mol)
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    if ci is None:
        ci = mc.ci
    if verbose is None:
        verbose = mc.verbose

    casdm1s, casdm2 = klaspdft_helper.make_one_casdm12_klas(
        mc, ci=ci, state=state,
    )
    mo_phase = klaspdft_helper.get_klas_mo_phase(
        mc, mo_coeff=mo_coeff,
    )
    e_mcwfn = mc.energy_mcwfn(
        mo_coeff=mo_coeff,
        ci=ci,
        ot=ot,
        state=state,
        casdm1s=casdm1s,
        casdm2=casdm2,
        verbose=verbose,
        mo_phase=mo_phase,
    )
    e_ot = mc.energy_dft(
        mo_coeff=mo_coeff,
        ci=ci,
        ot=ot,
        state=state,
        casdm1s=casdm1s,
        casdm2=casdm2,
        mo_phase=mo_phase,
    )
    e_tot = e_mcwfn + e_ot
    logger.note(
        mc,
        "kLAS-PDFT state %d E = %s, Eot(%s) = %s",
        state,
        e_tot,
        ot.otxc,
        e_ot,
    )
    return e_tot, e_ot


class _kLASPDFT(_kMCPDFT):
    """k-MC-PDFT specialization for periodic LASCI and LASSCF states."""

    make_one_casdm1s = klaspdft_helper.make_one_casdm1s_klas
    make_one_casdm2 = klaspdft_helper.make_one_casdm2_klas
    energy_mcwfn = energy_mcwfn_klas
    energy_dft = energy_dft_klas
    energy_tot = energy_tot_klas
