"""Periodic MC-PDFT wrappers and energy methods for kLAS wave functions.

This module specializes the existing k-MC-PDFT implementation for density
matrices produced by periodic LASCI and LASSCF.  kLAS RDMs and active-space
integrals use a Wannier basis, so the corresponding kLAS ``mo_phase`` is
carried explicitly into every basis transformation.
"""

import copy

import numpy as np

from pyscf import __config__
from pyscf.lib import logger
from pyscf.pbc.lib import kpts_helper

from mrh.my_pyscf.pbc.mcpdft import klaspdft_helper
from mrh.my_pyscf.pbc.mcpdft import kmcpdft
from mrh.my_pyscf.pbc.mcpdft.kmcpdft import _kMCPDFT
from mrh.my_pyscf.pbc.mcpdft.otfnalperiodic import _energy_ot_from_kpts


def energy_mcwfn_klas(mc, mo_coeff=None, ci=None, ot=None, state=0,
                      casdm1s=None, casdm2=None, verbose=None,
                      mo_phase=None):
    """Evaluate the MC-wavefunction energy from kLAS Wannier RDMs.

    This is the conventional dense-Wannier k-MC-PDFT energy expression with
    two kLAS-specific inputs: the phase generated by the kLAS Wannier routine
    and the full active-space integrals returned by ``get_h2cas``.
    """
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    if ci is None:
        ci = mc.ci
    if casdm1s is None or casdm2 is None:
        built_dm1s, built_dm2 = klaspdft_helper.make_one_casdm12_klas(
            mc, ci=ci, state=state,
        )
        if casdm1s is None:
            casdm1s = built_dm1s
        if casdm2 is None:
            casdm2 = built_dm2
    if mo_phase is None:
        mo_phase = klaspdft_helper.get_klas_mo_phase(
            mc, mo_coeff=mo_coeff,
        )
    h2eff = mc.get_h2cas(mo_coeff)
    return kmcpdft.energy_mcwfn(
        mc,
        mo_coeff=mo_coeff,
        ci=ci,
        ot=ot,
        state=state,
        casdm1s=casdm1s,
        casdm2=casdm2,
        verbose=verbose,
        mo_phase=mo_phase,
        h2eff=h2eff,
    )


def energy_dft_klas(mc, mo_coeff=None, ci=None, ot=None, state=0,
                    casdm1s=None, casdm2=None, max_memory=None, hermi=1,
                    mo_phase=None):
    """Evaluate the on-top functional from kLAS Wannier density matrices."""
    if ot is None:
        ot = mc.otfnal
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    if ci is None:
        ci = mc.ci
    if casdm1s is None or casdm2 is None:
        built_dm1s, built_dm2 = klaspdft_helper.make_one_casdm12_klas(
            mc, ci=ci, state=state,
        )
        if casdm1s is None:
            casdm1s = built_dm1s
        if casdm2 is None:
            casdm2 = built_dm2
    if mo_phase is None:
        mo_phase = klaspdft_helper.get_klas_mo_phase(
            mc, mo_coeff=mo_coeff,
        )
    if max_memory is None:
        max_memory = mc.max_memory

    kconserv = getattr(mc, "kconserv", None)
    if kconserv is None:
        kconserv = kpts_helper.get_kconserv(mc.cell, mc.kpts)
    casdm1s_kpts, cascm2_kpts = \
        klaspdft_helper.make_klas_rdms_kpts(
            casdm1s, casdm2, mo_phase, kconserv,
        )
    return _energy_ot_from_kpts(
        ot,
        casdm1s_kpts,
        cascm2_kpts,
        mo_coeff,
        mc.ncore,
        kconserv,
        max_memory=max_memory,
        hermi=hermi,
    )


def energy_tot_klas(mc, mo_coeff=None, ci=None, ot=None, state=0,
                    verbose=None, **kwargs):
    """Build one kLAS RDM pair and evaluate its total MC-PDFT energy.

    The expensive product-state RDMs and the gauge-defining ``mo_phase`` are
    each constructed once and shared by the MC-wavefunction and on-top energy
    paths.
    """
    del kwargs
    if ot is None:
        ot = mc.otfnal
    ot.reset(mol=mc.mol)
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    if ci is None:
        ci = mc.ci
    if verbose is None:
        verbose = mc.verbose

    casdm1s, casdm2 = klaspdft_helper.make_one_casdm12_klas(
        mc, ci=ci, state=state,
    )
    mo_phase = klaspdft_helper.get_klas_mo_phase(
        mc, mo_coeff=mo_coeff,
    )
    e_mcwfn = mc.energy_mcwfn(
        mo_coeff=mo_coeff,
        ci=ci,
        ot=ot,
        state=state,
        casdm1s=casdm1s,
        casdm2=casdm2,
        verbose=verbose,
        mo_phase=mo_phase,
    )
    e_ot = mc.energy_dft(
        mo_coeff=mo_coeff,
        ci=ci,
        ot=ot,
        state=state,
        casdm1s=casdm1s,
        casdm2=casdm2,
        mo_phase=mo_phase,
    )
    e_tot = e_mcwfn + e_ot
    logger.note(
        mc,
        "kLAS-PDFT state %d E = %s, Eot(%s) = %s",
        state,
        e_tot,
        ot.otxc,
        e_ot,
    )
    return e_tot, e_ot


class _kLASPDFT(_kMCPDFT):
    """k-MC-PDFT specialization for periodic LASCI and LASSCF states."""

    make_one_casdm1s = klaspdft_helper.make_one_casdm1s_klas
    make_one_casdm2 = klaspdft_helper.make_one_casdm2_klas
    energy_mcwfn = energy_mcwfn_klas
    energy_dft = energy_dft_klas
    energy_tot = energy_tot_klas


def get_klas_mcpdft_child_class(klas, ot, grids_level=None,
                                grids_attr=None, **kwargs):
    """Wrap a completed kLAS object with fixed-wavefunction PDFT methods.

    Unlike the conventional MC-PDFT child-class factory, this routine does not
    call the parent MC-SCF constructor.  Reconstructing a kLAS object would
    rebuild its fragment solvers and requires mesh-specific arguments.  A new
    dynamic child instead receives a shallow copy of the completed kLAS state,
    after which only the PDFT grids and bookkeeping fields are initialized.

    Parameters
    ----------
    klas : object
        Completed periodic LASCI or LASSCF calculation.
    ot : str or on-top functional
        Translated on-top functional specification.
    grids_level : int, optional
        Periodic integration-grid level.
    grids_attr : dict, optional
        Additional periodic integration-grid attributes.
    **kwargs
        Attribute overrides applied to the PDFT wrapper.

    Returns
    -------
    pdft : object
        A new kLAS-PDFT object.  Calling ``kernel`` evaluates PDFT without
        rerunning the underlying LASCI or LASSCF optimization.
    """
    mc_class = klas.__class__
    mc_doc = mc_class.__doc__ or "No docstring for kLAS parent method"

    class PDFT(_kLASPDFT, mc_class):
        __doc__ = mc_doc + "\n\n" + _kLASPDFT.__doc__
        _mc_class = mc_class

        @property
        def mol(self):
            """Molecular view of the primitive cell required by MC-PDFT."""
            return self._scf.cell.to_mol()

        def optimize_mcscf_(self, mo_coeff=None, ci0=None, **unused):
            """Reuse the fixed kLAS wave function without reoptimizing it."""
            if mo_coeff is not None:
                self.mo_coeff = mo_coeff
            if ci0 is not None:
                self.ci = ci0
            self.e_mcscf = self._klas_reference_energy
            return self

        def compute_pdft_energy_(
                self, mo_coeff=None, ci=None, ot=None, otxc=None,
                grids_level=None, grids_attr=None, dump_chk=False, **kw):
            """Evaluate and store fixed-wavefunction kLAS-PDFT energies."""
            if dump_chk:
                raise ValueError("dump_chk is not supported for kLAS-PDFT")
            return _kLASPDFT.compute_pdft_energy_(
                self,
                mo_coeff=mo_coeff,
                ci=ci,
                ot=ot,
                otxc=otxc,
                grids_level=grids_level,
                grids_attr=grids_attr,
                dump_chk=False,
                **kw,
            )

    pdft = PDFT.__new__(PDFT)
    pdft.__dict__ = copy.copy(klas.__dict__)
    pdft._keys = set(getattr(klas, "_keys", ()))
    pdft._keys.update({
        "e_ot", "e_mcscf", "e_states", "otfnal", "grids",
        "max_cycle_fp", "conv_tol_ci_fp", "mcscf_kernel",
        "_in_mcscf_env", "_klas_reference_energy",
    })
    pdft.max_cycle_fp = getattr(
        __config__, "mcscf_mcpdft_max_cycle_fp", 50,
    )
    pdft.conv_tol_ci_fp = getattr(
        __config__, "mcscf_mcpdft_conv_tol_ci_fp", 1e-8,
    )
    pdft.mcscf_kernel = mc_class.kernel
    pdft._in_mcscf_env = False
    pdft._klas_reference_energy = copy.copy(getattr(klas, "e_tot", None))
    pdft.e_mcscf = copy.copy(pdft._klas_reference_energy)
    pdft.e_ot = None

    if grids_attr is None:
        grids_attr = {}
    else:
        grids_attr = dict(grids_attr)
    if grids_level is not None:
        grids_attr["level"] = grids_level
    pdft._init_ot_grids(ot, grids_attr=grids_attr)
    for key, value in kwargs.items():
        if not hasattr(pdft, key):
            raise TypeError(f"Unknown kLAS-PDFT option: {key}")
        setattr(pdft, key, value)
    return pdft
