# /usr/bin/env python3

import numpy as np
import scipy.linalg
from functools import reduce
from itertools import product

from pyscf import lib
from pyscf.fci import cistring
from pyscf.pbc import scf, dft, df
from pyscf.pbc.lib import kpts_helper

from mrh.my_pyscf.mcscf import lasci as mollasci
from mrh.my_pyscf.mcscf.lasci import LASCINoSymm
from mrh.my_pyscf.mcscf.addons import state_average_n_mix, get_h1e_zipped_fcisolver

from mrh.my_pyscf.pbc.mcscf import casci
from mrh.my_pyscf.pbc.mcscf import klasci_guess
from mrh.my_pyscf.pbc.mcscf.productstate import ImpureProductStateFCISolver
from mrh.my_pyscf.pbc.mcscf.productstate import PBCTransSymmImpureProductStateFCISolver
from mrh.my_pyscf.pbc.util.transym import TranslationSymm
from mrh.my_pyscf.pbc.util import wannier
from mrh.my_pyscf.pbc.fci import csf_solver

check_h1e_translation = wannier.check_h1e_translation
check_h2e_translation = wannier.check_h2e_translation
check_wannier_orbital_translation = wannier.check_wannier_orbital_translation
get_wannier_orbs = wannier.get_wannier_orbs


# Author: Bhavnesh Jangid

'''
# Let's start implementing the k-LAS algorithm.
# Steps
1. Implement the k-LASCI
2. Implement the k-LASSCF
3. Implement the LASSI algorithm
'''

# Some global variable:
TRNS_SYMM_TOL = 1e-8


def kLASCI(kmf, ncas, nelecas, ncore=None, spin_mult=None, kmesh=None,
           kpts=None, trans_sym=False, ref_cell=0):
    '''
    Wrapper function for k-LASCI. 
    args:
        kmf: pbc.scf object
            mean-field object
        ncas: int
            number of active orbitals per unit cell
        nelecas: int/tuple
            number of active electrons per unit cell
        ncore: int, optional
            number of core orbitals per unit cell
        spin_mult: int, optional (2S + 1)
            spin multiplicity of the active space in the unit cell.
            If not provided, it will be automatically determined based 
            on the number of active electrons.
        kmesh: tuple, optional
            k-point mesh for the calculation.
        kpts: array_like, optional
            k-points for the calculation. 
        trans_sym: bool, optional
            If True, verify translation symmetry of the Wannier-basis one- and
            two-electron Hamiltonians before solving the product-state problem.
            # TODO: The CI-vectors would be stored for a reference cell only
            and the rest of the cells CI vector would be generated by translation symmetry.
        ref_cell: int, optional
            Reference-cell index for the translation-symmetric implementation.
            It is currently stored as metadata; all fragments are still solved.
    returns:
        klas: k-LASCI object
    '''
    assert isinstance(kmf, scf.hf.SCF),  \
        "k-LASCI only works with periodic SCF objects"
    
    if kmf.cell.symmetry:
        raise NotImplementedError("k-LASCI with symmetry is not implemented yet.")
    
    # Sanity check to make sure that DFT mean field objects are not passed to k-LASCI
    if isinstance(kmf, dft.krks.KRKS) or isinstance(kmf, dft.kuks.KUKS) \
        or isinstance(kmf, dft.rks.RKS) or isinstance(kmf, dft.uks.UKS):
        raise NotImplementedError("k-LASCI with DFT is not implemented yet.")
    
    # If the mean-field object is KUHF, convert it to RHF before passing to k-LASCI,
    if isinstance(kmf, scf.kuhf.KUHF):
        kmf = scf.addons.convert_to_rhf(kmf)
    
    # Currently, the k-LAS should work with the GDF density fitting object.
    assert isinstance(kmf.with_df, df.df.GDF), \
        "k-LASCI only works with GDF density fitting object"


    if not isinstance(trans_sym, (bool, np.bool_)):
        raise TypeError("trans_sym must be a boolean")
    if not isinstance(ref_cell, (int, np.integer)):
        raise TypeError("ref_cell must be an integer")
    if not trans_sym and ref_cell != 0:
        raise ValueError("ref_cell is only available when trans_sym=True")

    # I am making a big change here: as in defining the PBCLASCITransSymm class.
    # The CI vectors, mo_coeff, hamiltonian everything would be packed different in this
    # class.
    klas_cls = PBCLASCITransSymm if trans_sym else PBCLASCINoSymm
    klas = klas_cls(kmf, ncas, nelecas, ncore=ncore, spin_mult=spin_mult,
                    kmesh=kmesh, kpts=kpts,)

    if trans_sym:
        klas.set_ref_cell(ref_cell)

    return klas

@lib.with_doc(casci.h1e_for_cas.__doc__ + """

    Notes:
        Unlike k-CASCI, k-LASCI returns the active-space one-electron
        Hamiltonian in the Wannier basis. The frozen-core contribution and
        k-point AO-to-MO projection are shared with k-CASCI; only the final
        representation change is different.
""")
def h1e_for_cas(mc, mo_coeff=None, ncas=None, ncore=None):
    h1e_kpts, ecore = mc.h1e_kpts_for_cas(
        mo_coeff=mo_coeff, ncas=ncas, ncore=ncore,
    )
    h1eff_wann = _convert_h1e_mo_k_to_wann(
        mc._scf, mc.kmesh, h1e_kpts,
    )
    return h1eff_wann, ecore

@lib.with_doc(casci.PBCCASCI.get_h2eff.__doc__ + """

    Notes:
        This k-LASCI implementation returns the two-electron integrals in the
        Wannier basis. It first transforms the integrals to the k-point active
        MO basis and then applies the k-to-Wannier transformation.

    Args:
        mc : PBCCASCI
            Periodic CASCI object.
        mo_coeff : list or ndarray of shape (nkpts, nao, nmo)
            MO coefficients at each k-point. If not provided, ``mc.mo_coeff``
            is used.

    Returns:
        h2eff_R : ndarray
            Two-electron integrals in the Wannier basis with shape
            ``(nkpts*ncas, nkpts*ncas, nkpts*ncas, nkpts*ncas)``.
""")
def h2e_for_cas(mc, mo_coeff=None):
    kmf = mc._scf
    cell = kmf.cell
    ncore = mc.ncore
    ncas = mc.ncas
    nkpts = mc.nkpts
    kpts = kmf.kpts
    kmesh = mc.kmesh

    assert kmesh is not None

    kconserv = kpts_helper.get_kconserv(cell, kpts)
    
    if mo_coeff is None:
        mo_coeff = mc.mo_coeff
    
    # Do the ao2mo transformation in the k-space MO basis first to get eri_k, 
    # which is in the k-space MO basis.
    mo_act_kpts = np.array([mo_coeff[i][:, ncore:ncore+ncas] for i in range(nkpts)])

    #eri_k = kmf.with_df.ao2mo_7d(mo_act_kpts, kpts=kpts)
    from mrh.my_pyscf.pbc.df.df_ao2mo import ao2mo_7d
    eri_k = ao2mo_7d(kmf.with_df, mo_act_kpts, kpts=kpts)
    # Get the mo phase for the active space orbitals
    mo_phase = get_wannier_orbs(kmf, kmesh, mo_act_kpts)[-1]
    mo_ks = mo_phase[kconserv]

    # This einsum looks very scary but it is just the transformation of the eris from 
    # k-space mo to r-space mo.
    eris = np.einsum('auR,bvS,abcuvwt,cwT,abctU->RSTU',
                        mo_phase.conj(), mo_phase, eri_k, mo_phase.conj(), mo_ks, optimize=True)
    eris *= 1.0/nkpts
    
    assert eris.shape == (nkpts*ncas, nkpts*ncas, nkpts*ncas, nkpts*ncas)
    return eris

def _convert_h1e_mo_k_to_wann(kmf, kmesh, h1e_mo_k):
    '''
    Convert h1e from k-space localized/block MO basis to Wannier basis.
    args:
        kmf:
            PBC mean-field object.
        kmesh:
            k-point mesh.
        h1e_mo_k:
            ndarray of shape (nkpts, norb, norb)
    returns:
        h1eff_R:
            ndarray of shape (nkpts*norb, nkpts*norb)
    '''

    cell = kmf.cell
    kpts = kmf.kpts
    norb = h1e_mo_k.shape[1]
    dtype = np.result_type(h1e_mo_k.dtype, np.complex128)

    ts = TranslationSymm(cell, kmesh)
    R_indices = ts.R_indices
    R_cart = np.array([ts.lattice_cart(R) for R in R_indices])

    ncell = len(R_indices)
    nkpts = len(kpts)

    assert nkpts == np.prod(kmesh)
    assert ncell == nkpts

    h1e_mo_k = np.asarray(h1e_mo_k)
    assert h1e_mo_k.ndim == 3
    assert h1e_mo_k.shape[0] == nkpts
    assert h1e_mo_k.shape[1] == h1e_mo_k.shape[2]

    # h1eff_R = np.zeros((ncell, norb, ncell, norb), dtype=dtype)
    # for ik, k in enumerate(kpts):
    #     hk = h1e_mo_k[ik]
    #     for iR, Rv in enumerate(R_cart):
    #         for iS, Sv in enumerate(R_cart):
    #             phase = np.exp(1j * np.dot(k, Rv - Sv))
    #             h1eff_R[iR, :, iS, :] += phase * hk
    # h1eff_R /= nkpts
    phase_kR = np.exp(1j * np.einsum('kx,Rx->kR', kpts, R_cart))
    h1eff_R = np.einsum(
        'kR,kS,kij->RiSj',
        phase_kR, phase_kR.conj(), h1e_mo_k,
        optimize=True,
    ) / nkpts
    h1eff_R = h1eff_R.reshape(ncell * norb, ncell * norb)
    return h1eff_R

def _cell_average_dm1s(dm1s, nkpts):
    """Average the cell blocks of a Wannier density and repeat in every cell.

    The k-diagonal potential contains this cell-averaged density. We use it
    to restore the contribution from differences between cell densities.
    This is needed when CI vectors are not constrained by translation
    symmetry and give different cell densities, while the orbitals remain
    translation symmetric.
    This is an average over cells, in addition to the electronic-state
    averaging used in molecular LAS. The input density is cell diagonal.
    """
    dm1s = np.asarray(dm1s)
    ncas, remainder = divmod(dm1s.shape[-1], nkpts)
    if remainder or dm1s.shape[-2] != dm1s.shape[-1]:
        raise ValueError("Wannier density must contain equal-sized cell blocks")
    starts = range(0, dm1s.shape[-1], ncas)
    average = np.mean([
        dm1s[..., start:start+ncas, start:start+ncas] for start in starts
    ], axis=0)
    result = np.zeros(dm1s.shape, dtype=average.dtype)
    for start in starts:
        result[..., start:start+ncas, start:start+ncas] = average
    return result


@lib.with_doc(mollasci.h1e_for_las.__doc__ + """

    Notes:
        In the periodic implementation, ``mo_coeff`` has shape
        ``(nkpts, nao, nmo)`` and the active-space Hamiltonian and density
        matrices are represented in the Wannier basis. The k-space potential
        contains the cell-averaged density; the Wannier correction restores
        each state's full cell-dependent density before self-interaction is
        subtracted. A supplied ``veff`` must use the same AO density convention
        as ``make_rdm1s``.
""")
def h1e_for_las (las, mo_coeff=None, ncas=None, ncore=None, nelecas=None, 
                 ci=None, ncas_sub=None,
                 nelecas_sub=None, veff=None, h2eff_sub=None, casdm1s_sub=None, casdm1frs=None,
                 eri_cas=None):
    cell = las._scf.cell
    if mo_coeff is None: mo_coeff = las.mo_coeff
    if ncas is None: ncas = las.ncas
    if ncore is None: ncore = las.ncore
    if ncas_sub is None: ncas_sub = las.ncas_sub
    if nelecas_sub is None: nelecas_sub = las.nelecas_sub
    if ncore is None: ncore = las.ncore
    if ci is None: ci = las.ci
    if eri_cas is None: eri_cas = las.get_h2cas (mo_coeff)
    if casdm1frs is None: casdm1frs = las.states_make_casdm1s_sub (ci=ci)
    if casdm1s_sub is None: casdm1s_sub = [np.einsum ('rsij,r->sij',dm,las.weights)
                                           for dm in casdm1frs]
    if veff is None:
        veff = las.get_veff (cell, dm_kpts = las.make_rdm1s (mo_coeff=mo_coeff, casdm1s_sub=casdm1s_sub))
        # veff is in the k-space

    nkpts, nao, nmo = mo_coeff.shape
    ncore, ncas = las.ncore, las.ncas
    nocc = ncore + ncas
    ncastot = nkpts * ncas

    # First pass: split by root
    hcore_k = las.get_hcore()
    dtype = np.result_type(mo_coeff, hcore_k, veff, eri_cas, np.complex128)
    h1e_k = np.empty ((2, nkpts, ncas, ncas), dtype=dtype)
    for k in range(nkpts):
        mo_cas = mo_coeff[k][:, ncore:nocc]
        moH_cas = mo_cas.conj ().T
        h1e_k[:, k] = moH_cas @ (hcore_k[k][None,:,:] + veff[:, k, :, :]) @ mo_cas

    h1e_mo_wann = np.array([_convert_h1e_mo_k_to_wann(las._scf, las.kmesh, h1e_k[s]) 
                            for s in range(2)])
    h1e_k = hcore_k = None

    h1e_r = np.empty ((las.nroots, 2, ncastot, ncastot), dtype=h1e_mo_wann.dtype)

    assert (eri_cas.shape==(ncastot,ncastot,ncastot,ncastot))

    h2e = eri_cas

    # casdm1 is in wannier mo basis.
    avgdm1s = np.stack ([scipy.linalg.block_diag (*[dm[spin] for dm in casdm1s_sub])
                         for spin in range (2)], axis=0)
    # The AO k-diagonal potential contains the translation average, not the
    # full root-averaged density when different cells have different CI.
    cellavgdm1s = _cell_average_dm1s(avgdm1s, nkpts)
    for state in range (las.nroots):
        statedm1s = np.stack ([scipy.linalg.block_diag (*[dm[state][spin] for dm in casdm1frs])
                               for spin in range (2)], axis=0)
        dm1s = statedm1s - cellavgdm1s
        j = np.tensordot (dm1s, h2e, axes=((1,2),(2,3)))
        k = np.tensordot (dm1s, h2e, axes=((1,2),(2,1)))
        h1e_r[state] = h1e_mo_wann + j + j[::-1] - k

    # Second pass: split by fragment and subtract double-counting
    h1e_fr = []
    for ix, casdm1s_r in enumerate (casdm1frs):
        p = sum (las.ncas_sub[:ix])
        q = p + las.ncas_sub[ix]
        h1e = h1e_r[:,:,p:q,p:q]
        h2e = eri_cas[p:q,p:q,p:q,p:q]
        j = np.tensordot (casdm1s_r, h2e, axes=((2,3),(2,3)))
        k = np.tensordot (casdm1s_r, h2e, axes=((2,3),(2,1)))
        h1e_fr.append (h1e - j - j[:,::-1] + k)

    return h1e_fr

@lib.with_doc(mollasci.kernel.__doc__ + """

    Notes:
        This is the periodic k-LASCI kernel. The orbital coefficients carry a
        leading k-point dimension, and the reported total and CAS energies are
        normalized by the number of k-points.
""")
def kernel (las, mo_coeff=None, ci0=None, lroots=None, lweights=None, verbose=0,
               assert_no_dupes=False, _dry_run=False):
    if assert_no_dupes: mollasci.assert_no_duplicates (las)
    if lroots is not None and lweights is not None:
        raise RuntimeError ("lroots sets lweights: pass either or none but not both")
    elif lweights is None:
        if lroots is None: lroots = np.ones ((las.nfrags, las.nroots), dtype=int)
        lweights = []
        for i in range (las.nfrags):
            lwi = []
            for j in range (las.nroots):
                lwij = np.zeros (lroots[i,j])
                lwij[0] = 1
                lwi.append (lwij)
            lweights.append (lwi)
    
    nkpts, nao, nmo = mo_coeff.shape
    ncore, ncas = las.ncore, las.ncas
    nocc = ncore + ncas
    ncas_sub = las.ncas_sub
    nelecas_sub = las.nelecas_sub
    orbsym = getattr (mo_coeff, 'orbsym', None)
    if orbsym is not None: orbsym=orbsym[ncore:nocc]
    elif isinstance (las, mollasci.LASCISymm):
        mo_coeff = las.label_symmetry_(mo_coeff)
        orbsym = mo_coeff.orbsym[ncore:nocc]
    log = lib.logger.new_logger (las, verbose)

    h1eff, energy_core = las.h1e_for_cas (mo_coeff=mo_coeff,
        ncas=las.ncas, ncore=las.ncore)
    eri_cas = las.get_h2cas (mo_coeff)

    phase_per_frag = None
    if isinstance(las, PBCLASCITransSymm):
        las._sanity_check_trans_symmetry(mo_coeff, h1eff, eri_cas)
        phase_per_frag = las.get_phase_per_frag(mo_coeff)
    
    if (ci0 is None or any ([c is None for c in ci0]) or
            any ([any ([c2 is None for c2 in c1]) for c1 in ci0])):
        ci0 = las.get_init_guess_ci (mo_coeff, ci0=ci0, eri_cas=eri_cas)

    e_cas = np.empty (las.nroots, dtype=h1eff.dtype)
    e_states = np.empty (las.nroots, dtype=h1eff.dtype)
    ci1 = [[None for c2 in c1] for c1 in ci0]
    converged = []
    t = (lib.logger.process_clock(), lib.logger.perf_counter())
    e_lexc = [[None for i in range (las.nroots)] for j in range (las.nfrags)]
    for state in range (las.nroots):
        fcisolvers = [b.fcisolvers[state] for b in las.fciboxes]
        ci0_i = [c[state] for c in ci0]
        if isinstance(las, PBCLASCITransSymm):
            solver = PBCTransSymmImpureProductStateFCISolver(
                fcisolvers, stdout=las.stdout,
                lweights=[l[state] for l in lweights], verbose=verbose,
                ref_cell=las.ref_cell,
                phase_per_frag=phase_per_frag,
                pack_h1=las.pack_h1,
                pack_h2=las.pack_h2,
            )
        else:
            solver = ImpureProductStateFCISolver(
                fcisolvers, stdout=las.stdout,
                lweights=[l[state] for l in lweights], verbose=verbose,
            )
        for ix, s in enumerate (solver.fcisolvers):
            # Set the calling las objects local bottom-layer fcisolvers to the
            # locally-state-averaged ones I just made so that I can more easily get
            # locally-state-averaged density matrices after this function exits
            las.fciboxes[ix].fcisolvers[state] = s
            i = sum (ncas_sub[:ix])
            j = i + ncas_sub[ix]
            if orbsym is not None: s.orbsym = orbsym[i:j]
            s.norb = ncas_sub[ix]
            s.nelec = solver._get_nelec (s, nelecas_sub[ix])
            s.check_transformer_cache ()
        if _dry_run: continue
        conv, e_i, ci_i = solver.kernel (h1eff, eri_cas, ncas_sub, nelecas_sub,
            ecore=0, ci0=ci0_i, orbsym=orbsym, conv_tol_grad=las.conv_tol_grad,
            conv_tol_self=las.conv_tol_self, max_cycle_macro=las.max_cycle_macro)
        e_cas[state] = e_i
        e_states[state] = e_i + energy_core
        for frag, s in enumerate (solver.fcisolvers):
            e_loc = np.atleast_1d (getattr (s, 'e_states', e_i))
            e_lexc[frag][state] = e_loc - e_i
        for c1, c2, s, no, ne in zip (ci1, ci_i, solver.fcisolvers, ncas_sub, nelecas_sub):
            ne = solver._get_nelec (s, ne)
            ndeta, ndetb = [cistring.num_strings (no, n) for n in ne]
            shape = [s.nroots, ndeta, ndetb] if s.nroots>1 else [ndeta, ndetb]
            c1[state] = np.asarray (c2).reshape (*shape)
        if not conv: log.warn ('State %d LASCI not converged!', state)
        converged.append (conv)
        t = log.timer ('State {} LASCI'.format (state), *t)

    if not _dry_run:
        e_states /= nkpts
        e_cas /= nkpts
        e_lexc = [[np.asarray(e) / nkpts for e in frag]
                  for frag in e_lexc]
    e_tot = np.dot (las.weights, e_states)
    return converged, e_tot, e_states, e_cas, e_lexc, ci1


def _convert_dmao_R_to_dmao_k(kmf, kmesh, dm_R):
    '''
    Convert the density matrix from real space to k-space.
    '''

    cell = kmf.cell
    kpts = kmf.kpts
    dtype = dm_R.dtype
    
    ts = TranslationSymm(cell, kmesh)
    R_indices = ts.R_indices
    R_cart = np.array([ts.lattice_cart(R) for R in R_indices])

    nkpts = len(kpts)
    assert nkpts == np.prod(kmesh) == len(R_cart)
    assert dm_R.ndim == 2

    nao = dm_R.shape[0] // nkpts
    assert nao == cell.nao_nr()

    dm_R = dm_R.reshape(nkpts, nao, nkpts, nao)
    # dm_k = np.zeros((nkpts, nao, nao), dtype=dtype)
    # for ik, k in enumerate(kpts):
    #     for iR, Rv in enumerate(R_cart):
    #         phase_R = np.exp(-1j * np.dot(k, Rv))
    #         for iS, Sv in enumerate(R_cart):
    #             phase_S = np.exp(+1j * np.dot(k, Sv))
    #             dm_k[ik] += phase_R * dm_R[iR, :, iS, :] * phase_S
    # dm_k /= nkpts  # Remember the normalization.
    phase_kR = np.exp(1j * np.einsum('kx,Rx->kR', kpts, R_cart))
    dm_k = np.einsum(
        'kR,RiSj,kS->kij',
        phase_kR.conj(), dm_R, phase_kR,
        optimize=True,
    ) / nkpts
    dm_k = dm_k.astype(dtype, copy=False)
    return dm_k

class PBCLASCINoSymm(casci.PBCCASCI, LASCINoSymm):
    '''
    Localized active space CI (LASCI) class for periodic systems without 
    point group symmetry.
    args:
        kmf: pbc.scf object
            mean-field object
        ncas: int
            number of active orbitals per unit cell
        nelecas: int/tuple
            number of active electrons per unit cell
        spin_mult: int, optional (2S + 1)
            spin multiplicity of the active space in the unit cell.
            If not provided, it will be automatically determined based 
            on the number of active electrons.
        ncore: int, optional
            number of core orbitals per unit cell
        kmesh: tuple, optional
            k-point mesh for the calculation.
        kpts: array_like, optional
            k-points for the calculation.
    '''

    # Currently initializing the LASCINosymm is breaking a lot of things in
    # PBCCASCI module. As an example, the fcisolver class is reassigned to direct_spin1 or the
    # real csf_solver. so I decided to adopt the __init__ function of the LASCINoSymm class and 
    # then register the functions that I need from PBCCASCIForLAS to this class. 
    # This is not a clean way to do it but it is the fastest way to get it working. I will refactor this later.


    def __init__(self, kmf, ncas, nelecas, ncore=None, spin_mult=None,
                 kmesh=None, kpts=None, frozen=None, frozen_ci=None, **kwargs):
        self.init_guess_ci = 'aufbau1'
        self.nroots = 1 # This line is required before initializing the parent class, because of self.converged ..
        casci.PBCCASCI.__init__(self, kmf, ncas, nelecas, ncore=ncore)
        self.chkfile = self._scf.chkfile
        if isinstance(nelecas, int):
            na = nelecas // 2
            nb = nelecas - na
            nelecas = (na, nb)
        elif isinstance(nelecas, tuple) and len(nelecas) == 2:
            nelecas = tuple(nelecas)
        
        assert kmesh is not None
        nkpts = np.prod(kmesh)
        if kpts is None:
            kpts = kmf.kpts

        nkpts_check = len(kpts)
        assert nkpts_check == nkpts, "kmesh and kpts do not match."
        self.kmesh = kmesh
        self.kpts = kpts

        if spin_mult is None: spin_mult = 1 + abs(nelecas[0]-nelecas[1])
        spin_sub = [spin_mult,] * nkpts
        self.ncas_sub = np.asanyarray(nkpts * (ncas,))
        self.nelecas_sub = np.asarray([(nelecas),] * nkpts)
        assert (len (self.nelecas_sub) == self.nfrags)
        self.frozen = frozen
        self.frozen_ci = frozen_ci
        self.conv_tol_grad = 1e-4
        self.conv_tol_self = 1e-10
        self.ah_level_shift = 1e-8
        self.max_cycle_macro = 50
        self.max_cycle_micro = 5
        self.min_cycle_macro = 0
        self.trust_radius = np.pi
        keys = set(('e_states', 'fciboxes', 'nroots', 'weights', 'ncas_sub', 'nelecas_sub',
                    'conv_tol_grad', 'conv_tol_self', 'max_cycle_macro', 'max_cycle_micro',
                    'ah_level_shift', 'states_converged', 'chkfile', 'e_lexc', 'trust_radius'))
        self._keys = set(self.__dict__.keys()).union(keys)
        self.fciboxes = []
        if isinstance(spin_sub,int):
            self.fciboxes.append(self._init_fcibox(spin_sub,self.nelecas_sub[0]))
        else:
            assert (len (spin_sub) == self.nfrags)
            for smult, nel in zip (spin_sub, self.nelecas_sub):
                self.fciboxes.append (self._init_fcibox (smult, nel))
        self.weights = [1.0]
        self.e_states = [0.0]
        self.e_lexc = [[np.array ([0]),],]
    
    def _init_fcibox(self, smult, nelec):
        '''
        Initialize a FCI box for a given spin multiplicity and electron count.
        This has to replaced from the standard LASCI implementation.
        '''
        solver = csf_solver(self.cell, smult)
        solver.spin = nelec[0] - nelec[1]
        return get_h1e_zipped_fcisolver(state_average_n_mix(self, [solver], [1.0]).fcisolver)

    @property
    def kpts(self):
        '''K-points used by both the mean-field and k-LASCI calculations.'''
        return np.array(self._scf.kpts, copy=True)

    @kpts.setter
    def kpts(self, value):
        value = np.asarray(value)
        kmf_kpts = np.asarray(self._scf.kpts)
        if (value.shape != kmf_kpts.shape
                or not np.allclose(value, kmf_kpts, atol=1e-10, rtol=0.0)):
            msg = "kpts must match kmf.kpts in shape, ordering, and values; "
            msg += f"got shapes {value.shape} and {kmf_kpts.shape}"
            raise ValueError(msg)

    # Register these functions.
    get_sym_fr = LASCINoSymm.get_sym_fr
    get_nelec_frs = LASCINoSymm.get_nelec_frs
    get_h1eff = get_h1las = h1e_for_las = h1e_for_las
    get_h2eff = ao2mo = LASCINoSymm.get_h2eff
    get_h2eff_slice = LASCINoSymm.get_h2eff_slice
    get_h1cas = h1e_for_cas = h1e_for_cas 
    get_h2cas = h2e_for_cas = h2e_for_cas 
    localize_init_guess = klasci_guess.localize_init_guess
    
    @lib.with_doc(kernel.__doc__ + """

        Notes:
            This method stores the results returned by the module-level
            periodic k-LASCI kernel on the current object.
    """)
    def kernel (self, mo_coeff=None, ci0=None, lroots=None, lweights=None, verbose=None,
               assert_no_dupes=False, _dry_run=False):
        nkpts = len(self.kpts)
        if mo_coeff is None:
            mo_coeff=self.mo_coeff
        else:
            self.mo_coeff = mo_coeff
        assert nkpts == mo_coeff.shape[0]

        if ci0 is None: ci0 = self.ci
        if verbose is None: verbose = self.verbose
        converged, e_tot, e_states, e_cas, e_lexc, ci = kernel (
            self, mo_coeff=mo_coeff, ci0=ci0, lroots=lroots, lweights=lweights,
            verbose=verbose, assert_no_dupes=assert_no_dupes, _dry_run=_dry_run)
        if _dry_run: return
        self.converged, self.ci = converged, ci
        self.e_tot, self.e_states, self.e_cas, self.e_lexc = e_tot, e_states, e_cas, e_lexc
        if mo_coeff is self.mo_coeff:
            pass
            # self.dump_chk ()
        elif getattr (self, 'chkfile', None) is not None:
            lib.logger.warn (self, 'orbitals changed; chkfile not dumped!')
        self._finalize (method='LASCI')
        return (self.converged, self.e_tot, self.e_states, self.e_cas,
                self.e_lexc, self.ci)

    def _finalize(self, method='LASCI'):
        log = lib.logger.new_logger (self, self.verbose)
        nroots_prt = len (self.e_states)
        if self.verbose <= lib.logger.INFO:
            nroots_prt = min (nroots_prt, 100)
        if nroots_prt < len (self.e_states):
            log.info (("Printing a maximum of 100 state energies;"
                    " increase self.verbose to see them all"))
        if nroots_prt > 1:
            log.info ("%s state-average energy = %.15g", method, self.e_tot)
            for i, e in enumerate (self.e_states[:nroots_prt]):
                log.info ("%s state %d energy = %.15g", method, i, e)
        else:
            log.info ("%s energy = %.15g", method, self.e_tot.real)
        return
    
    def get_mo_slice (self, idx, mo):
        '''
        Get the molecular orbital slice for a given fragment.
        Note, unlinke molecular LASCI, the mo_coeff are only passed in 
        for the active space part only.
        '''
        for offs in self.ncas_sub[:idx]:
            mo = mo[:,offs:]
        mo = mo[:,:self.ncas_sub[idx]]
        return mo
    
    @lib.with_doc(mollasci.LASCINoSymm.make_casdm1s_sub.__doc__ + """

        Notes:
            The returned fragment density matrices are expressed in the
            Wannier active-orbital basis.
    """)
    def make_casdm1s_sub (self, ci=None, ncas_sub=None, nelecas_sub=None,
            casdm1frs=None, w=None, **kwargs):
        if casdm1frs is None:
            casdm1frs = self.states_make_casdm1s_sub (ci=ci, ncas_sub=ncas_sub, 
                                                      nelecas_sub=nelecas_sub, **kwargs)
        if w is None: w = self.weights
        # (nfrags, 2, ncas, ncas), this would be wannier basis
        return [np.einsum ('rspq,r->spq', dm1, w) for dm1 in casdm1frs]
    
    def make_rdm1s_sub (self, mo_coeff=None, ci=None, ncas_sub=None,
            nelecas_sub=None, include_core=False, casdm1s_sub=None, **kwargs):
        
        if mo_coeff is None: mo_coeff = self.mo_coeff
        if ci is None: ci = self.ci
        if ncas_sub is None: ncas_sub = self.ncas_sub
        if nelecas_sub is None: nelecas_sub = self.nelecas_sub
        if casdm1s_sub is None: casdm1s_sub = self.make_casdm1s_sub (ci=ci,
            ncas_sub=ncas_sub, nelecas_sub=nelecas_sub, **kwargs)
        
        # We would need to transform the casdm1s to the AO basis, so using wannierization.
        nkpts, nao, nmo = mo_coeff.shape
        ncas = ncas_sub[0]
        ncore = self.ncore
        mo_act_kpts = [mo_coeff[i][:, ncore:ncore+ncas] for i in range(nkpts)]
        wannier_orb = get_wannier_orbs(self._scf, self.kmesh, mo_act_kpts)[0]
        wannier_orb = wannier_orb.reshape(nkpts*nao, nkpts*ncas)
        
        # These should be in wannier basis.
        rdm1s_ao_wann = []
        for idx, casdm1s in enumerate (casdm1s_sub):
            mo = self.get_mo_slice (idx, wannier_orb)
            moH = mo.conjugate ().T
            # Fragment RDMs use the energy-contraction convention. Transpose
            # their orbital indices to obtain the AO density used by JK.
            rdm1s_ao_wann.append(np.array([reduce(np.dot, (mo, casdm1s[s].T, moH))
                                           for s in range(2)]))
            
        rdm1s_ao_wann = np.array(rdm1s_ao_wann).sum (0)
        
        assert rdm1s_ao_wann.shape == (2, nkpts*nao, nkpts*nao), \
            f"Shape mismatch: {rdm1s_ao_wann.shape} != (2, {nkpts*nao}, {nkpts*nao})"
        
        rdm1s_ao_k = np.array([
            _convert_dmao_R_to_dmao_k(self._scf, self.kmesh, rdm1s_ao_wann[s]) 
            for s in range(2)])
        
        assert rdm1s_ao_k.shape == (2, nkpts, nao, nao), \
            f"Shape mismatch: {rdm1s_ao_k.shape} != (2, {nkpts}, {nao}, {nao})"

        if include_core and self.ncore:
            for k in range(nkpts):
                mo_core = mo_coeff[k][:,:self.ncore]
                moH_core = mo_core.conjugate ().T
                dm_core = mo_core @ moH_core
                rdm1s_ao_k[:, k, :, :] += np.array([dm_core, dm_core])

        # Sanity Checks: compare the number of electrons from the density matrix.        
        assert rdm1s_ao_k.shape == (2, nkpts, nao, nao), \
            f"Shape mismatch: {rdm1s_ao_k.shape} != (2, {nkpts}, {nao}, {nao})"

        coreelec = 0 if include_core else self.ncore * 2
        ovlp = self._scf.get_ovlp(kpts=self.kpts)
        rdm1 = rdm1s_ao_k.sum (0)
        nelecref = self._scf.cell.nelectron
        nelecdiff = [np.trace(ovlp[k] @ rdm1[k]).real + coreelec - nelecref 
                    for k in range(nkpts)]
        if any(abs(diff) > 1e-6 for diff in nelecdiff):
            raise ValueError(f"Number of electrons mismatch for k-points: {nelecdiff}")
        return rdm1s_ao_k
    
    def make_rdm1s (self, mo_coeff=None, ncore=None, **kwargs):
        '''
        Get spin-separated, rootspace- and locally state-averaged 1-RDMs in the AO basis.
        Kwargs:
            mo_coeff: ndarray of shape (nkpts,nao,nmo)
                Contains MO coefficients at each k-point. If None, it will be taken from the PBCCASCI object.
            ncore: integer
                Number of core orbitals
        Returns:
            dm1s: ndarray of shape (2,nkpts,nao,nao)
                Rootspace- and locally state-averaged, spin-separated 1-RDMs in the AO basis for each k-point.
                Note: the casdm1s are constructed in the Wannier basis which are then transformed to block AO basis
                and then transformed to k-space. The core contribution is added in k-space.
        '''
        if mo_coeff is None: mo_coeff = self.mo_coeff
        if ncore is None: ncore = self.ncore
        nkpts = mo_coeff.shape[0]
        dtype = np.result_type(mo_coeff[0][0].dtype, np.complex128)
        dm_core = np.array([mo_coeff[k][:,:ncore] @ mo_coeff[k][:,:ncore].conj().T 
                            for k in range(nkpts)], dtype=dtype)
        dm_cas = self.make_rdm1s_sub (mo_coeff=mo_coeff, **kwargs)
        dm1s = dm_core[None,:,:] + dm_cas
        return dm1s
    
    def states_make_casdm1s_sub (self, ci=None, ncas_sub=None, nelecas_sub=None, **kwargs):
        if ci is None: ci = self.ci
        if ncas_sub is None: ncas_sub = self.ncas_sub
        if nelecas_sub is None: nelecas_sub = self.nelecas_sub
        dtype = np.complex128
        if ci is None:
            return [np.zeros ((self.nroots,2,ncas,ncas), dtype=dtype) for ncas in ncas_sub] 
        casdm1s = []
        for fcibox, ci_i, ncas, nelecas in zip (self.fciboxes, ci, ncas_sub, nelecas_sub):
            if ci_i is None:
                shape = (self.nroots, ncas, ncas)
                dm1a = dm1b = np.zeros (shape, dtype=dtype)
            else:
                dm1a, dm1b = fcibox.states_make_rdm1s (ci_i, ncas, nelecas)
            casdm1s.append (np.stack ([dm1a, dm1b], axis=1))
        return casdm1s


class PBCLASCITransSymm(PBCLASCINoSymm):
    '''
    Translation-symmetric adapted periodic LASCI implementation.

    This class currently enforces translation-symmetry prerequisites and
    validates the Wannier orbitals and Hamiltonians. Translation-packed state
    and integral representations can be added here without changing the
    general ``PBCLASCINoSymm`` implementation.
    '''

    trans_sym = True
    ref_cell = 0

    def set_ref_cell(self, ref_cell):
        '''Set the representative BvK-cell index.'''
        if not isinstance(ref_cell, (int, np.integer)):
            msg = f"ref_cell must be an integer, got {type(ref_cell)}"
            raise TypeError(msg)
        ncell = int(np.prod(self.kmesh))
        if not 0 <= ref_cell < ncell:
            msg = f"ref_cell must be in [0, {ncell}); got {ref_cell}"
            raise ValueError(msg)
        self.ref_cell = int(ref_cell)
        self._keys.add("ref_cell")
        return self

    def get_phase_per_frag(self, lo_coeff, tol=TRNS_SYMM_TOL):
        '''Get translated fragment-CI phases from the localized orbitals.

        The phase for each fragment is obtained by translating the reference
        Wannier orbitals into that fragment and comparing the two orbital
        coefficient tensors.  This returns a scalar CI phase only when all
        active orbitals share one common translation phase.  A general orbital
        rotation must instead be lifted to the determinant basis.

        The returned phase accounts for the fixed number of active electrons
        in each fragment and can be passed to ``_unpack_cif``.
        '''
        lo_coeff = np.asarray(lo_coeff)
        self._sanity_check_active_space_consistency(lo_coeff)

        active = slice(self.ncore, self.ncore + self.ncas)
        wannier_orb, R_indices = get_wannier_orbs(
            self._scf, self.kmesh, lo_coeff[:, :, active],
        )[:2]
        ts = TranslationSymm(
            self.cell, self.kmesh, kpts=self.kpts,
        )
        R_to_i = ts.index_map(R_indices)
        ref_R = R_indices[self.ref_cell]
        ref_orb = wannier_orb[:, :, self.ref_cell, :]

        phases = np.empty(ts.ncell, dtype=np.complex128)
        for ifrag, frag_R in enumerate(R_indices):
            translation = frag_R - ref_R
            source_cells = [
                R_to_i[ts.mod_index(R - translation)]
                for R in R_indices
            ]
            translated_ref = ref_orb[source_cells]
            target = wannier_orb[:, :, ifrag, :]

            overlap = np.vdot(translated_ref, target)
            if abs(overlap) == 0:
                raise RuntimeError(
                    f"zero translated-orbital overlap for fragment {ifrag}"
                )
            orbital_phase = overlap / abs(overlap)
            error = np.linalg.norm(
                target - orbital_phase * translated_ref
            ) / max(np.linalg.norm(target), 1e-14)
            if error >= tol:
                msg = "translated active orbitals for fragment "
                msg += f"{ifrag} require a non-scalar transformation "
                msg += f"(relative error {error:.3e})"
                raise RuntimeError(msg)

            nelec = int(np.sum(self.nelecas_sub[ifrag]))
            phases[ifrag] = orbital_phase.conjugate() ** nelec

        phases[self.ref_cell] = 1.0
        return phases

    def pack_h1(self, h1e):
        '''
        Pack a translation-symmetric one-electron Hamiltonian.

        The final two axes of ``h1e`` are interpreted as composite
        ``(cell, orbital)`` indices.  The packed result has shape
        ``(..., ncell, ncas, ncas)`` and stores

            h1_packed[dS, p, q] = h1[ref, p, ref + dS, q].

        Any leading axes, such as a spin axis, are retained.
        '''
        h1e = np.asarray(h1e)
        ncell = int(np.prod(self.kmesh))
        ncas = self.ncas
        ncas_tot = ncell * ncas
        if h1e.ndim < 2 or h1e.shape[-2:] != (ncas_tot, ncas_tot):
            msg = "h1e must end in shape "
            msg += f"({ncas_tot}, {ncas_tot}); got {h1e.shape}"
            raise ValueError(msg)

        ts = TranslationSymm(self.cell, self.kmesh, kpts=self.kpts)
        h1_blocks = h1e.reshape(
            h1e.shape[:-2] + (ncell, ncas, ncell, ncas)
        )
        h1_packed = np.empty(
            h1e.shape[:-2] + (ncell, ncas, ncas), dtype=h1e.dtype,
        )
        ref_R = ts.R_indices[self.ref_cell]
        for idelta, delta in enumerate(ts.R_indices):
            iS = ts.R_to_i[ts.mod_index(ref_R + delta)]
            h1_packed[..., idelta, :, :] = h1_blocks[
                ..., self.ref_cell, :, iS, :
            ]
        return h1_packed

    def pack_h2(self, h2e):
        '''
        Pack a translation-symmetric two-electron Hamiltonian.

        The final four axes of ``h2e`` are composite ``(cell, orbital)``
        indices.  The packed result has shape
        ``(..., ncell, ncell, ncell, ncas, ncas, ncas, ncas)`` and stores

            h2_packed[dS,dU,dV,p,q,r,s]
                = h2[ref,p,ref+dS,q,ref+dU,r,ref+dV,s].

        Any leading axes are retained.
        '''
        h2e = np.asarray(h2e)
        ncell = int(np.prod(self.kmesh))
        ncas = self.ncas
        ncas_tot = ncell * ncas
        expected = (ncas_tot,) * 4
        if h2e.ndim < 4 or h2e.shape[-4:] != expected:
            msg = f"h2e must end in shape {expected}; got {h2e.shape}"
            raise ValueError(msg)

        ts = TranslationSymm(self.cell, self.kmesh, kpts=self.kpts)
        h2_blocks = h2e.reshape(
            h2e.shape[:-4] + (ncell, ncas) * 4
        )
        h2_packed = np.empty(
            h2e.shape[:-4]
            + (ncell, ncell, ncell, ncas, ncas, ncas, ncas),
            dtype=h2e.dtype,
        )
        ref_R = ts.R_indices[self.ref_cell]
        translated_cells = [
            ts.R_to_i[ts.mod_index(ref_R + delta)]
            for delta in ts.R_indices
        ]
        # for idS, iS in enumerate(translated_cells):
        #     for idU, iU in enumerate(translated_cells):
        #         for idV, iV in enumerate(translated_cells):
        #             h2_packed[..., idS, idU, idV, :, :, :, :] = (
        #                 h2_blocks[
        #                     ..., self.ref_cell, :, iS, :, iU, :, iV, :
        #                 ]
        #             )
        translated_cell_triplets = list(
            product(enumerate(translated_cells), repeat=3)
        )
        for ((idS, iS), (idU, iU),
             (idV, iV)) in translated_cell_triplets:
            h2_packed[..., idS, idU, idV, :, :, :, :] = h2_blocks[
                ..., self.ref_cell, :, iS, :, iU, :, iV, :
            ]
        return h2_packed
    
    def _sanity_check_active_space_consistency(self, mo_coeff):
        '''
        Validate that every translated cell has the same active space
        and that the number of k-points, LAS fragments, and FCI boxes are
        consistent with the number of translated cells.
        '''
        ncell = int(np.prod(self.kmesh))
        problems = []

        if not 0 <= self.ref_cell < ncell:
            msg = f"ref_cell ({self.ref_cell}) must be in [0, {ncell})"
            problems.append(msg)

        if len(self.kpts) != ncell:
            msg = f"number of k-points ({len(self.kpts)}) != ncell ({ncell})"
            problems.append(msg)

        if self.nfrags != ncell:
            msg = f"number of LAS fragments ({self.nfrags}) != ncell ({ncell})"
            problems.append(msg)

        if len(self.fciboxes) != ncell:
            msg = f"number of FCI boxes ({len(self.fciboxes)}) != ncell ({ncell})"
            problems.append(msg)

        ncas_sub = np.asarray(self.ncas_sub)
        if ncas_sub.shape != (ncell,) or np.any(ncas_sub != self.ncas):
            msg = f"all translated cells must have the same number of active \
                orbitals ({self.ncas}); got {ncas_sub.tolist()}"
            problems.append(msg)

        nelecas_sub = np.asarray(self.nelecas_sub)
        if (nelecas_sub.shape != (ncell, 2)
                or np.any(nelecas_sub != nelecas_sub[0])):
            msg = "all translated cells must have identical active-electron "
            msg += f"counts; got {nelecas_sub.tolist()}"
            problems.append(msg)

        mo_coeff = np.asarray(mo_coeff)
        if mo_coeff.ndim != 3 or mo_coeff.shape[0] != ncell:
            msg = f"mo_coeff must have shape (ncell, nao, nmo); got {mo_coeff.shape}"
            problems.append(msg)
        elif self.ncore + self.ncas > mo_coeff.shape[2]:
            msg = "mo_coeff does not contain the complete core and active spaces"
            problems.append(msg)

        # Now print the problems and raise an error if there are any.
        if problems:
            msg = "Translation-symmetric active-space consistency check failed:\n"
            for problem in problems:
                msg += f"  - {problem}\n"
            raise ValueError(msg)

    def _sanity_check_trans_symmetry(self, mo_coeff, h1e, h2e, tol=TRNS_SYMM_TOL):
        '''
        Check the translation symmetry of the active-space, Wannier-orbital, 
        h1e, and h2e.
        
        args:
            mo_coeff: ndarray of shape (nkpts, nao, nmo) (# Block orb basis)
                Molecular orbital coefficients for each k-point.
            h1e: ndarray of shape (ncell*ncas, ncell*ncas)
                One-electron Hamiltonian in the Wannier basis.
            h2e: ndarray of shape (ncell*ncas, ncell*ncas, ncell*ncas, ncell*ncas)
                Two-electron Hamiltonian in the Wannier basis.
            tol: float
                Tolerance for checking translation symmetry.
        '''
        self._sanity_check_active_space_consistency(mo_coeff)

        ts = TranslationSymm(self.cell, self.kmesh, kpts=self.kpts)
        active = slice(self.ncore, self.ncore + self.ncas)
        mo_active = np.asarray(mo_coeff)[:, :, active]

        # Get the Wannier orbitals.
        wannier_orb, R_indices = get_wannier_orbs(self._scf, self.kmesh, mo_active,)[:2]

        # Check every nontrivial primitive translation of the BvK mesh.  For a
        # one-cell mesh, retain an identity check to validate tensor shapes.
        translations = [tuple(int(i == axis) for i in range(3))
                        for axis, size in enumerate(self.kmesh) if size > 1]
        if not translations:
            translations = [(1, 0, 0)]

        errors = {'Wannier orbitals': None, 'h1e': None, 'h2e': None}
        failed = []
        for translation in translations:
            errors_T = {
                'Wannier orbitals': check_wannier_orbital_translation(
                    ts, wannier_orb, R_indices=R_indices,T_index=translation, tol=tol,),
                'h1e': check_h1e_translation(ts, h1e, T_index=translation, tol=tol,),
                'h2e': check_h2e_translation(ts, h2e, T_index=translation, tol=tol,),
            }

            for name, error in errors_T.items():
                if errors[name] is None or error[1] > errors[name][1]:
                    errors[name] = error
                if error[1] >= tol:
                    msg = f"{name} under T_index={translation} (relative error {error[1]:.3e})"
                    failed.append(msg)
                        
        if failed:
            msg = "Wannier-basis translation symmetry check failed for "
            msg += " and ".join(failed)
            raise RuntimeError(msg)

        # Clean up large temporary variables while retaining the diagnostics.
        del failed, wannier_orb, R_indices, mo_active, ts, translations
        return errors
